### ISSUE TITLE
NixOS test issues

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TankDriver#11]
Currently the tests fail on NixOS with mono 4.0.1:

``` console
$ mono ../../../packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./TankDriver.Tests.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.17020)
System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
```

It seems like we hit [xunit#158](https://github.com/xunit/xunit/issues/158) that was fixed somewhere around mono 4.2. Unstable NixOS channel have [mono 4.4](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/mono/4.4.nix) already, but the stable channel doesn't.

What options do we have? We wanna run these tests without problems. Rely our build on `mono44` and recommend the users to use unstable channel? Could it be done in a user-friendly manner?

**Comment by ForNeVeR** [comment]
Probably we should depend on `mono44` and recommend our users to clone the current nixpkgs and then invoke

``` console
$ nix-shell /path/to/nixpkgs
```

**Comment by rexim** [comment]
@ForNeVeR sounds good to me. Let me check if such approach works on my setup

**Comment by ForNeVeR** [comment]
It'll take a long time to compile unstable Mono (with all the dependencies) on a stable system. Make sure to prepare enough tea for that!

**Comment by rexim** [comment]
@ForNeVeR sure! :)

**Comment by rexim** [comment]
Ok, I cloned nixpkgs and after `nix-shell ./nixpkgs` I saw:

```
error: Package ‘Agda-Sheaves-8a06162a8f0f7df308458db91d720cf8f7345d69’ in ‘./nixpkgs/pkgs/development/libraries/agda/Agda-Sheaves/default.nix:18’ is marked as broken, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.
```

Alright, I allowed broken packages in `~/.nixpkgs/config.nix` as it was advised and repeated the process:

```
error: while evaluating the attribute ‘bedup’ at ./nixpkgs/lib/attrsets.nix:199:44:
while evaluating anonymous function at ./nixpkgs/lib/meta.nix:42:54, called from ./nixpkgs/lib/attrsets.nix:199:52:
while evaluating ‘isDerivation’ at ./nixpkgs/lib/attrsets.nix:295:18, called from ./nixpkgs/lib/meta.nix:42:62:
while evaluating the attribute ‘bedup’ at ./nixpkgs/pkgs/top-level/python-packages.nix:1993:3:
while evaluating ‘makeOverridable’ at ./nixpkgs/lib/customisation.nix:54:24, called from ./nixpkgs/pkgs/top-level/python-packages.nix:1993:11:
while evaluating anonymous function at ./nixpkgs/pkgs/development/python-modules/generic/default.nix:9:1, called from ./nixpkgs/lib/customisation.nix:56:12:
bedup-0.10 not supported for interpreter python2.7
```

Ok, I stopped at this point and don't wanna continue.

I had another idea about patching the current mono expression from `default.nix`. I will try to experiment in that direction later today.

**Comment by rexim** [comment]
I managed to override mono via `~/.nixpkgs/config.nix` and successfully execute unit tests on NixOS 16.03. I will check if the entire development setup is still stable enough and prepare instructions later.
