### ISSUE TITLE
Define a license for the artwork

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TankDriver#31]
Currently we have no artistic license applied, so [these masterpieces](https://github.com/ForNeVeR/TankDriver/tree/815984119463c8ab3328f339d2bf0023e1a213fb/TankDriver.App/Content/Tank) (and also [this one](https://github.com/ForNeVeR/TankDriver/blob/815984119463c8ab3328f339d2bf0023e1a213fb/TankDriver.App/Content/Bullet/Bullet.png)) thus have unclear legal status.

Let's use [cc-by](https://creativecommons.org/licenses/by/4.0/) license for the artwork.

@rexim, are you agree to relicense your present artistic contributions in this project under the terms of [cc-by](https://creativecommons.org/licenses/by/4.0/)?

**Comment by rexim** [comment]
@ForNeVeR yes, I agree to relicense my present artistic contributions in this project under the terms of cc-by.

**Comment by ForNeVeR** [comment]
Thanks!
