### ISSUE TITLE
Replace ImageMagick with something else

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TankDriver#35]
See
- https://github.com/vvvv/SVG
- https://sharpvectors.codeplex.com/

**Comment by rexim** [comment]
@ForNeVeR what's the reason of such decision? Licensing? Specific bugs of ImageMagick?

**Comment by ForNeVeR** [comment]
The main reason in the maintenance cost. Making our build rely on a tool installed globally on user's machine is generally a bad idea. Yesterday I had a complaint from a potential contributor: they weren't able to build the project due to lack of ImageMagick on their machine. And anything that causes contributor loss is, in my opinion, a critical issue and should be addressed ASAP.

Our build process should be as much self-contained as possible, i.e. the user shouldn't need to install any additional tools except from what we expect the ordinary .NET (or Mono) developer to have on their machine.

**Comment by rexim** [comment]
@ForNeVeR sounds reasonable. Thanks for the explanation. I can help with testing all of that on NixOS in the future.
