### ISSUE TITLE
Add shooting

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TankDriver#5]
On mouse click the tank should shoot a bullet object that dies when goes outside of the screen. Bullet direction should correspond to the tank turret direction at the moment of fire.

Everything else (like bullet interaction with other objects) is the scope of other issues that have to be
created.

**Comment by rexim** [comment]
Taking this one

**Comment by rexim** [comment]
I propose the following scope for this issue:

```
On some button the tank should shoot a bullet object that dies when
goes outside of the screen. Everything else (like bullet interaction
with other objects) is the scope of other issues that have to be
created.
```

@ForNeVeR, are you ok with this scope?

**Comment by ForNeVeR** [comment]
Yep.

**Comment by ForNeVeR** [comment]
Updated the first post.
